# Generated by Django 3.1.2 on 2020-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ID',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
    ]
