# Generated by Django 3.1.2 on 2020-11-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20201108_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='books.Genre', verbose_name='Жанр'),
        ),
    ]
