# Generated by Django 3.1.2 on 2020-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201108_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='aaaa', max_length=100, unique=True, verbose_name='Полное имя'),
        ),
    ]
